# Ontario

## Research questions

```{r label = "global-options", include=FALSE}

### setting up working environment
### for details see: https://yihui.name/knitr/options/
knitr::opts_chunk$set(
        collapse = T,
        echo = F,
        message = T,
        error = T,
        warning = T,
        comment = '##',
        highlight = T,
        prompt = F,
        strip.white = T,
        tidy = T
        )

### installing and loading packages

# If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
if (!require("plyr"))
        {install.packages("plyr", repos = 'http://cran.wu.ac.at/')
        library(plyr)}

### https://www.tidyverse.org/
if (!require("tidyverse"))
        {install.packages("tidyverse", repos = 'http://cran.wu.ac.at/')
        library(tidyverse)}

### above command installed and loaded the core tidyverse packages:
# ggplot2: data visualization
# tibble:  a modern take on data frames
# tidyr:   data tidying
# readr:   data import (csv, tsv, fwf)
# purrr:   functional R programming
# dplyr:   data (frame) manipulation
# stringr: string manipulation
# forcats: working with categorical variables

# I am going to use the `janitor` package for calculating table totals
if (!require("janitor"))
        {install.packages("janitor", repos = 'http://cran.wu.ac.at/')
        library(janitor)}

if (!require("reshape2"))
        {install.packages("reshape2", repos = 'http://cran.wu.ac.at/')
        library(reshape2)}

if (!require("readODS"))
        {install.packages("readODS", repos = 'http://cran.wu.ac.at/')
        library(readODS)}

### generate my theme
my_theme <- theme_light() +
        theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5)) +
        theme(plot.background = element_rect(color = NA, fill = NA)) +
        theme(plot.margin = margin(1, 0, 0, 0, unit = 'cm'))

### global variables

vec.subject.short = c("Business", "Arts", "IT", "Law", "Earth", "Health", "History", "Language", "Literature", "Math", "Medicine", "Philosophy", "Reference", "Society", "Technology")

vec.subject.long = c("Business & Management", "The Arts", "Computing & IT", "Law", "Earth & Environment", "Health & Development", "History", "Language & Linguistics", "Literature", "Mathematics & Science", "Medicine & Nursing", "Philosophy & Religion", "Reference", "Society & Social Sciences", "Technology & Engineering")

vec.question.set = c("Drag and Drop", "Drag Text", "Essay", "Fill in the Blanks", "Mark the Words",
                 "Multiple Choice", "True/False Question")
vec.course.presentation =  c("Dialog Cards", "Drag and Drop", "Drag Text", "Fill in the Blanks",
                         "Interactive Video", "Mark the Words", "Multiple Choice", "Single Choice Set",
                         "Summary", "True/False Question")
vec.interactive.video =  c("Drag and Drop", "Drag Text", "Essay", "Fill in the Blanks", "Image Hotspots",
                        "Mark the Words", "Multiple Choice", "Questionnaire", "Single Choice Set",
                        "Summary", "True/False Question")
vec.compounds =  c("Dialog Cards", "Drag and Drop", "Drag Text", "Essay", "Fill in the Blanks", 
                   "Interactive Video", "Image Hotspots", "Mark the Words", "Multiple Choice", 
                   "Questionnaire", "Single Choice Set", "Summary", "True/False Question")
vec.compound.names = c("Question Set", "Course Presentation", "Interactive Video")
```

## Stand-alone distribution of H5P content types


```{r stand-alone}

#########    read data for overall content types   ###############
library(readODS)
df.sa.type <- read_ods(
    path = "ontario_data/H5P-Content-Types-2020-10-13.ods",
    sheet = 2,
    )


#########     read data for content types by discipline ##########
df.sa.subject <- read_ods(
    path = "ontario_data/H5P-Content-Types-2020-10-13.ods",
    sheet = 3,
    )

### LOOK HERE and the next few lines
df.sa.subject <- adorn_totals(df.sa.subject, where = "row", name = "Total")

df.sa.subject.sum <-  df.sa.subject %>%
#    adorn_totals(where = "row", name = "Total") %>%
    filter(ContentType == "Total") %>% 
    select(all_of(vec.subject.short)) %>% 
    gather(all_of(vec.subject.short), key = "Discipline", value = "Total") %>% 
    mutate(Discipline = vec.subject.long)



#########      READ DATA FOR COMPOUND CONTENT TYPES          ################



#################        QUESTION SET            ########################

# see: https://stackoverflow.com/questions/17499013/how-do-i-make-a-list-of-data-frames
LL.Question.Sets =  list()
sheetNames <- list_ods_sheets("ontario_data/Question-Set-2020-10-14.ods")
i <- length(sheetNames)
for(i in 2:i){                             # i start with 2 because first sheet = Intro
    LL.Question.Sets[[i-1]] <-                 # but list starts with 1
        read_ods(             
                path = "ontario_data/Question-Set-2020-10-14.ods",
                sheet = i
                )
}
### see: https://stackoverflow.com/questions/20987295/rename-multiple-columns-by-names
names(LL.Question.Sets) <- vec.subject.short

#################        COURSE PRESENTATION        ########################

LL.Course.Presentations =  list()
sheetNames <- list_ods_sheets("ontario_data/Course-Presentation-2020-10-15.ods")
i <- length(sheetNames)
for(i in 2:i){                          
    LL.Course.Presentations[[i-1]] <-  read_ods(             
                path = "ontario_data/Course-Presentation-2020-10-15.ods",
                sheet = i
                )
}
names(LL.Course.Presentations) <- vec.subject.short

##################        INTERACTIVE VIDEO        ########################

LL.Interactive.Videos =  list()
sheetNames <- list_ods_sheets("ontario_data/Interactive-Video-2020-10-16.ods")
i <- length(sheetNames)
for(i in 2:i){                             
    LL.Interactive.Videos[[i-1]] <-read_ods(             
                path = "ontario_data/Interactive-Video-2020-10-16.ods",
                sheet = i
                )
}

names(LL.Interactive.Videos) <- vec.subject.short

##################        MULTIPLE CONTENT TYPES        ########################

### some CTs are counted multiple times when ordered by subject
LL.Multiple.Values =  list()
sheetNames <- list_ods_sheets("ontario_data/Content-Types-multiple.ods")
i <- length(sheetNames)
for(i in 2:i){                             
    LL.Multiple.Values[[i-1]] <-read_ods(             
                path = "ontario_data/Content-Types-multiple.ods",
                sheet = i
                )
}

names(LL.Multiple.Values) <- vec.compound.names


```



```{r test1, eval=FALSE, fig.height=2, fig.width=5}
library(tidyverse)

df = tribble(
  ~Type, ~N,
  "A", 72,
  "B", 14,
  "C", 25,
  "D",  9
)

ggplot(df, aes(x=Type, y=N)) +
  geom_bar(stat="identity") +
  coord_flip() +
  scale_x_discrete(expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(expand = expansion(mult = c(0, .05)))
  

ggplot(mtcars) +
  geom_bar(aes(x = factor(cyl))) +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  scale_x_discrete(expand = expansion(mult = c(0, 0)))


# scale_y_discrete(expand = expansion(mult = c(0, .05)), limits=c(0, 20,40, 60))
```

```{r test2, eval=FALSE}
library(gcookbook)
# cabbage_exp
ce <-  arrange(cabbage_exp, Date, Cultivar)
ce <- mutate(ce, label_y=cumsum(Weight))
# ce <- plyr::ddply(ce, "Date", transform, label_y=cumsum(Weight))
Cultivar1 <-  factor(ce$Cultivar, levels = c("c52", "c39"))
ggplot(ce, aes(x=Date, y=Weight, fill=Cultivar1)) +
  geom_bar(stat="identity") +
#  coord_flip() +
  geom_text(aes(y=label_y, label=Weight), vjust=1.5, colour="white")


df.test <-  df.overall[c(1,11,35, 40), ]
df.test1 <-  pivot_longer(df.test, c(Stand.Alone, Compounds), names_to = "Trait", values_to = "Count")
df.test2 <-  arrange(df.test1, ContentType, Trait)
Trait <- factor(df.test1$Trait, levels = c("Stand.Alone", "Compounds"))
df.test4 <-  plyr::ddply(df.test1, "ContentType", transform, label_y=cumsum(Count))
df.test3 <-  mutate(df.test1, label_y=cumsum(Count))


my.fun <- function(a, b) {
  for(i in 1:length(a)){
    # browser()
    if(a[i] == b[i]) {b[i] <-  b[i]-30}
    if(a[i] == 0){b[i] <-  -30}
    # if(a[i] != b[i] && a[i] != 0) {b[i] <-  b[i] +30 }
  }
  return (b)
}

my.fun <- function(trait, n, cum) {
  for(i in 1:length(trait)){
    if(trait[i] == "Stand.Alone") {n[i] <- -30}
    if(trait[i] == "Compounds") {n[i] <- cum[i] +30}
  }
  return (n)
}

df.test <-  df.overall[c(1,11,35,40), ]
df.test1 <-  pivot_longer(df.test, c(Stand.Alone, Compounds), names_to = "Trait", values_to = "Count")
# df.test2 <-  arrange(df.test1, ContentType, Trait)
# Trait <- factor(df.test1$Trait, levels = c("Stand.Alone", "Compounds"))
# df.test4 <-  plyr::ddply(df.test1, "ContentType", transform, label_y=cumsum(Count))
df <-  mutate(df.test1, new = my.fun(Trait, df.test1$Count, Total))

# df <-  mutate(df.test4, new = my.fun(Trait, df.test4$Count, df.test4$label_y))


ggplot(df, aes(x=ContentType, y=Count, fill=Trait)) +
  geom_bar(stat="identity") +
  coord_flip() +
  geom_text(aes(y=new, label=Count))

ggplot(df.test3, aes(x=ContentType, y=Count, fill=Trait)) +
  geom_bar(stat="identity") +
#  coord_flip() +
  geom_text(aes(y=label_y, label=Count))



ggplot(df.test5, aes(x=ContentType, y=Count, fill=Trait)) +
  geom_bar(stat="identity") +
#  coord_flip() +
  geom_text(aes(y=label_correct, label=Count))

ggplot(df.test, aes(x=ContentType, y=Count, fill=Trait)) +
  geom_bar(stat="identity") +
#  coord_flip() +
  geom_text(aes(y=label_y, label=Count))

dfx <- data.frame(
  group = c(rep('A', 8), rep('B', 15), rep('C', 6)),
  sex = sample(c("M", "F"), size = 29, replace = TRUE),
  age = runif(n = 29, min = 18, max = 54)
)

dfx1 <- ddply(dfx, .(group, sex), summarize,
 mean = round(mean(age), 2),
 sd = round(sd(age), 2))

my.fun <- function(a, b) {
  for(i in 1:length(a)){
    # browser()
    if(a[i] == 0){
      b[i] <-  0
    }
 }
  return(b)
}



my.fun(c(199,0),c(199,199))

```


## Distribution in Course Presentations

```{r prepare-plot}

######      bind all total cols   ######################
df.QS.total =  as_tibble(bind_cols(LL.Question.Sets))
df.QS.total = select(df.QS.total, c(1,starts_with("Total")))
names(df.QS.total) <- c("ContentType", vec.subject.short)

df.CP.total =  as_tibble(bind_cols(LL.Course.Presentations))
df.CP.total = select(df.CP.total, c(1,starts_with("Total")))
names(df.CP.total) <- c("ContentType", vec.subject.short)

df.IV.total =  as_tibble(bind_cols(LL.Interactive.Videos))
df.IV.total = select(df.IV.total, c(1,starts_with("Total")))
names(df.IV.total) <- c("ContentType", vec.subject.short)

##############  reshape data from wide to long  #############


df.QS.long <- melt(df.QS.total, 
                      id.vars = "ContentType",
                      variable.name = "Discipline",
                      value.name = "n")

df.CP.long <- melt(df.CP.total, 
                      id.vars = "ContentType",
                      variable.name = "Discipline",
                      value.name = "n")

df.IV.long <- melt(df.IV.total, 
                      id.vars = "ContentType",
                      variable.name = "Discipline",
                      value.name = "n")

### LOOK HERE and the next few lines
df.sa.subject.long <- melt(df.sa.subject, 
                      id.vars = "ContentType",
                      variable.name = "Discipline",
                      value.name = "n")


```
## Add compounds

```{r add-compounds-data}

### prepare df for union: 
df.QS.total <-  adorn_totals(df.QS.total, "col")
df.CP.total <-  adorn_totals(df.CP.total, "col")
df.IV.total <-  adorn_totals(df.IV.total, "col")

df.compounds <- 
    tibble(ContentType = vec.compounds) %>% 
    full_join(df.QS.total[, c(1,17)], by = "ContentType") %>% 
    full_join(df.CP.total[, c(1,17)], by = "ContentType") %>% 
    full_join(df.IV.total[, c(1,17)], by = "ContentType") %>% 
    adorn_totals("col", name = "Overall")

df.overall <-  
    full_join(df.sa.type, df.compounds[, c(1,5)], by = "ContentType") %>% 
    full_join(LL.Multiple.Values$`Interactive Video`[, c(1, 
                         ncol(LL.Multiple.Values$`Interactive Video`))],
                         by = "ContentType") %>% 
    replace_na(list(Overall.y = 0, Total = 0)) %>% 
    mutate(Overall = Overall.y - Total) %>% 
    select(c(-Overall.y, -Total)) %>% 
    rename("Stand.Alone" = Overall.x, "Compounds" = Overall) %>% 
    # select(c(-Overall.y, -Total)) %>% 
    # rename("Stand.Alone" = Overall.x, "Compounds" = Overall,
    #        "Sum.Multiple" = Overall.y, "Diff" = "Total") %>% 
    adorn_totals("col") 

df.overall.long <- gather(df.overall,
                          `Stand.Alone`, `Compounds`, key = "CT", value = N)
    

```


## Display and save plots

```{r display-save-plots, fig.height = 8, fig.width=8}

##########              CONTENT TYPES STAND-ALONE          ###############

ggplot(df.sa.type, aes(x=reorder(`ContentType`, Overall), y=Overall)) + 
    geom_bar(stat="identity", width = .7, fill= "#2fbfc4", colour = "#2fbfc4") +
    coord_flip() +
    my_theme +
    xlab("Name of H5P Content Types") +
    ylab("Number of Content Types") +
    ggtitle("Distribution of H5P Stand-alone Content Types in the Ontario Repository (2020-10-13)") +
    geom_text(aes(label=Overall), size=2.5, hjust=-0.2) +
    theme(plot.margin = margin(12,12,12,12)) +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05)))


ggsave("ontario_plots/CT_sa_type.pdf",
    width = 8,
    height = 8
    )

##########              CONTENT TYPES BY SUBJECT  SUM        ###############

ggplot(df.sa.subject.sum, aes(x=reorder(Discipline, Total), y = Total)) +
    geom_bar(stat="identity", width = .7, fill= "#2fbfc4", colour = "#2fbfc4") +
    coord_flip() +
    my_theme +
    xlab("Discipline") +
    ylab("Number of Content Types in the Ontario Repository") +
    ggtitle("H5P Content Types by Discipline in the Ontario Repository") +
    geom_text(aes(label=Total), size=3, hjust=-0.3) +
    theme(plot.margin = margin(12,12,12,12)) +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05)))

ggsave(    
    filename = "ontario_plots/CT_sa_subject_sum.pdf",
    width = 10,
    height = 5
    )

##########              CONTENT TYPES BY SUBJECT DETAIL       ###############

### LOOK HERE and the next few lines
ggplot(df.sa.subject.long, aes(x=reorder(Discipline, n), y = n)) +
    geom_bar(stat="identity", width = .7, fill= "#2fbfc4", colour = "#2fbfc4") +
    coord_flip() +
    my_theme +
    xlab("Discipline") +
    ylab("Number of Content Types in the Ontario Repository") +
    ggtitle("H5P Content Types by Discipline in the Ontario Repository") +
    geom_text(aes(label=n), size=3, hjust=-0.2) +
    theme(plot.margin = margin(12,12,12,12)) +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05)))

ggsave(    
    filename = "ontario_plots/CT_sa_subject.pdf",
    width = 10,
    height = 5
    )

##########              QUESTION SET          ###############

########## QUESTION SET: TYPE  ##########

ggplot(df.QS.long, aes(x=ContentType, y=n, fill=Discipline)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Question Sets") +
    ylab("Number of Content Types used within Question Sets") +
    ggtitle("Usage of H5P Content Types within Question Sets at the Ontario Repository") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
    
ggsave(    
    filename = "ontario_plots/CT_QS_type.pdf",
    width = 10,
    height = 5
    )

########## QUESTION SET: SUBJECT  ##########

ggplot(df.QS.long, aes(x=Discipline, y=n, fill=ContentType)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Question Sets by Discipline") +
    ylab("Number of Content Types used within Question Sets") +
    ggtitle("H5P Content Types within Question Sets by Discipline at the Ontario Repository") +
    scale_fill_discrete(name = "Content Types in\nQuestion Sets") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
ggsave(    
    filename = "ontario_plots/CT_QS_subject.pdf",
    width = 10,
    height = 5
    )

##########      COURSE PRESENTATION          ###############


########## COURSE PRESENTATION: TYPE  ##########

ggplot(df.CP.long, aes(x=ContentType, y=n, fill=Discipline)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Course Presentation") +
    ylab("Number of Content Types used within Course Presentation") +
    ggtitle("Usage of H5P Content Types within Course Presentation at the Ontario Repository") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
    
ggsave(    
    filename = "ontario_plots/CT_CP_type.pdf",
    width = 10,
    height = 5
    )

########## COURSE PRESENTATION: SUBJECT  ##########

ggplot(df.CP.long, aes(x=Discipline, y=n, fill=ContentType)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Course Presentation by Discipline") +
    ylab("Number of Content Types used within Course Presentation") +
    ggtitle("H5P Content Types within Course Presentation by Discipline at the Ontario Repository") +
    scale_fill_discrete(name = "Content Types in 
Course Presentation") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
ggsave(    
    filename = "ontario_plots/CT_CP_subject.pdf",
    width = 10,
    height = 5
    )



##########      INTERACTIVE VIDEO          ###############

########## INTERACTIVE VIDEO: TYPE  ##########

ggplot(df.IV.long, aes(x=ContentType, y=n, fill=Discipline)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Interactive Video") +
    ylab("Number of Content Types used within Interactive Video") +
    ggtitle("Usage of H5P Content Types within Interactive Video at the Ontario Repository") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
    
ggsave(    
    filename = "ontario_plots/CT_IV_type.pdf",
    width = 10,
    height = 5
    )

########## INTERACTIVE VIDEO: SUBJECT  ##########

ggplot(df.IV.long, aes(x=Discipline, y=n, fill=ContentType)) +
    geom_bar(stat="identity") +
    my_theme +
    xlab("H5P Content Types used within Interactive Video by Discipline") +
    ylab("Number of Content Types used within Interactive Video") +
    ggtitle("H5P Content Types within Interactive Video by Discipline at the Ontario Repository") +
    scale_fill_discrete(name = "Content Types in 
Interactive Video") +
    theme(axis.text.x = element_text(angle=50,hjust=1),
          plot.margin = margin(12,12,12,12))
ggsave(    
    filename = "ontario_plots/CT_IV_subject.pdf",
    width = 10,
    height = 5
    )

##############      ALL TOGETHER: DIFFERENT VARIANTS       ##################

##############      ALL TOGETHER, NO STACKED BARS         ##################

#### only one bar, but with totals
ggplot(df.overall, aes(x=reorder(ContentType, Total), y = Total)) +
    geom_bar(stat="identity", width = .8, fill= "#2fbfc4", colour = "#2fbfc4") +
    coord_flip() +
    my_theme +
    xlab("Content Types") +
    ylab("Number of Content Types in the Ontario Repository") +
    ggtitle("H5P Content Types (Stand-alone and Compounds) in the Ontario Repository") +
    geom_text(aes(label=Total), size=2.5, hjust=-0.5) +
    theme(plot.margin = margin(12,12,12,12)) +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05)))

ggsave(
    filename = "ontario_plots/CT_overall_not_stacked.pdf",
    width = 8,
    height = 8
    )

##############      ALL TOGETHER, STACKED BARS/NO SUMS         ##################

#### stacked bars, but without totals
ggplot(df.overall.long, aes(x=reorder(ContentType, N), y = N, fill = CT)) +
    geom_bar(stat="identity", width = .8) +
    coord_flip() +
    my_theme +
    labs(x = "Content Type", 
         y = "Number of Content Types in the Ontario Repository",
         title = "Content Types (Stand-Alone and Compounds) in the Ontario Repository",
         fill = "Content Types:"
         ) +
#    geom_text is wrong with IV, DD, DT, MW etc.
#    geom_text(aes(y=label_y, label=N), size=2.5, hjust=-0.5) +
    theme(plot.margin = margin(12,12,12,12),
            legend.position = "top") +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05))) +
    scale_fill_discrete(labels =c("Compound", "Stand Alone")) +
    guides(fill = guide_legend(reverse=TRUE))


ggsave(
    filename = "ontario_plots/CT_overall-stacked.pdf",
    width = 8,
    height = 8.2
    )




##########      STACKED BAR WITH 2 NUMBERS: sa and compounds        ###############



my.fun <- function(trait, n, cum) {
  for(i in 1:length(trait)){
    if(trait[i] == "Stand.Alone") {
      n[i] <- -5
    }

    if(trait[i] == "Compounds") {
      if(n[i] >= 100) {n[i] <-cum[i] +35}
      if(n[i] <= 100 && n[i] >= 10) {n[i] <- cum[i] +25}
      if(n[i] < 10) {n[i] <- cum[i] +15}
    }
  }
  return (n)
}

df <-  mutate(df.overall.long, label_y = my.fun(CT, N, Total))

ggplot(df, aes(x=reorder(ContentType, Total), y=N, fill=CT)) +
  geom_bar(stat="identity", width = .8) +
  coord_flip() + 
  my_theme +
  labs(x = "Content Type", 
       y = "Number of Content Types in the Ontario Repository",
       title = "Content Types (Stand-Alone and Compounds) in the Ontario Repository",
       fill = "Content Types:"
       ) +
  geom_text(aes(y=label_y, label=N), size=2.5, hjust = 1) +
  theme(plot.margin = margin(12,12,12,12),
        legend.position = "top",
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_fill_discrete(labels =c("Compound", "Stand Alone")) +
  scale_y_continuous(expand = expansion(mult = c(.04, 0.02))) +
  guides(fill = guide_legend(reverse=TRUE))

ggsave(    
    filename = "ontario_plots/CT_sa_compound.pdf",
    width = 8,
    height = 8
    )

##########      STACKED BAR WITH 3 NUMBERS: sa and compounds / overall       ###############



my2.fun <- function(trait, n, cum) {
  for(i in 1:length(trait)){
    if(trait[i] == "Stand.Alone") {
      n[i] <- -5
    }

    if(trait[i] == "Compounds") {
      s <- paste0(n[i], cum[i])
      if(nchar(s) >= 6){n[i] <-cum[i] +70}
      if(nchar(s) == 5){n[i] <-cum[i] +65}
      if(nchar(s) == 4){n[i] <-cum[i] +60}
      if(nchar(s) == 3){n[i] <-cum[i] +50}
      if(nchar(s) == 2){n[i] <-cum[i] +40}
    }
  }
  return (n)
}

df <-  mutate(df.overall.long, label_y = my2.fun(CT, N, Total))
df.final <- mutate(df, Overall = ifelse(CT == "Compounds", paste0(N, "/", Total), as.character(N)))

ggplot(df.final, aes(x=reorder(ContentType, Total), y=N, fill=CT)) +
  geom_bar(stat="identity", width = .8) +
  coord_flip() + 
  my_theme +
  labs(x = "Content Type", 
       y = "Number of Content Types in the Ontario Repository",
       title = "Content Types (Stand-Alone and Compounds) in the Ontario Repository",
       fill = "Content Types:"
       ) +
  geom_text(aes(y=label_y, label=Overall), size=2.5, hjust = 1) +
  theme(plot.margin = margin(12,12,12,12),
        legend.position = "top",
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_fill_discrete(labels =c("Compound / Overall", "Stand Alone")) +
  scale_y_continuous(expand = expansion(mult = c(.04, 0.02))) +
  guides(fill = guide_legend(reverse=TRUE))

ggsave(    
    filename = "ontario_plots/CT_overall.pdf",
    width = 8,
    height = 8
    )



##########      NOT STACKED ALL TOGETHER: OLD ORDER         ###############


df.overall.old.order <- bind_cols(df.overall, Overall = df.sa.type$Overall)
ggplot(df.overall.old.order, aes(x=reorder(ContentType, Overall), y = Total)) +
    geom_bar(stat="identity", width = .8, fill= "#2fbfc4", colour = "#2fbfc4") +
    coord_flip() +
    my_theme +
    xlab("Content Types") +
    ylab("Number of Content Types in the Ontario Repository") +
    ggtitle("H5P Content Types (Stand-alone and Compounds) in the Ontario Repository,
            ordered by the number of Stand-alone Content Types") +
    geom_text(aes(label=Total), size=2.5, hjust=-0.5) +
    theme(plot.margin = margin(12,12,12,12)) +
    scale_x_discrete(expand = expansion(mult = c(0, 0))) +
    scale_y_continuous(expand = expansion(mult = c(0, .05)))

ggsave(
    filename = "ontario_plots/CT_overall_old_order.pdf",
    width = 8,
    height = 8
    )



```


```{r}
sum(df.overall$Total)
```

